// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/convert.dart';
import 'api/textlayer.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<OcrProgress> dco_decode_StreamSink_ocr_progress_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<Progress> dco_decode_StreamSink_progress_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ConvertReport dco_decode_box_autoadd_convert_report(dynamic raw);

  @protected
  ConvertReport dco_decode_convert_report(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<PageText> dco_decode_list_page_text(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TextBox> dco_decode_list_text_box(dynamic raw);

  @protected
  OcrProgress dco_decode_ocr_progress(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  OutFormat dco_decode_out_format(dynamic raw);

  @protected
  PageText dco_decode_page_text(dynamic raw);

  @protected
  Progress dco_decode_progress(dynamic raw);

  @protected
  TextBox dco_decode_text_box(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<OcrProgress> sse_decode_StreamSink_ocr_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<Progress> sse_decode_StreamSink_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ConvertReport sse_decode_box_autoadd_convert_report(
    SseDeserializer deserializer,
  );

  @protected
  ConvertReport sse_decode_convert_report(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<PageText> sse_decode_list_page_text(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TextBox> sse_decode_list_text_box(SseDeserializer deserializer);

  @protected
  OcrProgress sse_decode_ocr_progress(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  OutFormat sse_decode_out_format(SseDeserializer deserializer);

  @protected
  PageText sse_decode_page_text(SseDeserializer deserializer);

  @protected
  Progress sse_decode_progress(SseDeserializer deserializer);

  @protected
  TextBox sse_decode_text_box(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_ocr_progress_Sse(
    RustStreamSink<OcrProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_progress_Sse(
    RustStreamSink<Progress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_convert_report(
    ConvertReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_convert_report(ConvertReport self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_page_text(List<PageText> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_text_box(List<TextBox> self, SseSerializer serializer);

  @protected
  void sse_encode_ocr_progress(OcrProgress self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_out_format(OutFormat self, SseSerializer serializer);

  @protected
  void sse_encode_page_text(PageText self, SseSerializer serializer);

  @protected
  void sse_encode_progress(Progress self, SseSerializer serializer);

  @protected
  void sse_encode_text_box(TextBox self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
