// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/convert.dart';
import 'api/textlayer.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 111713429;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'scanbridge',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<ConvertReport> crateApiConvertConvertForTest({
    required String modelDir,
    required List<String> images,
    required String outDir,
    required String title,
  });

  Stream<Progress> crateApiConvertConvertImages({
    required String modelDir,
    required List<String> images,
    required String outDir,
    required String title,
    required OutFormat format,
    required int longEdge,
    required bool lowMemory,
  });

  Stream<OcrProgress> crateApiTextlayerOcrImages({
    required String modelDir,
    required List<String> images,
    required int longEdge,
    required bool lowMemory,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<ConvertReport> crateApiConvertConvertForTest({
    required String modelDir,
    required List<String> images,
    required String outDir,
    required String title,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelDir, serializer);
          sse_encode_list_String(images, serializer);
          sse_encode_String(outDir, serializer);
          sse_encode_String(title, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_convert_report,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiConvertConvertForTestConstMeta,
        argValues: [modelDir, images, outDir, title],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConvertConvertForTestConstMeta =>
      const TaskConstMeta(
        debugName: "convert_for_test",
        argNames: ["modelDir", "images", "outDir", "title"],
      );

  @override
  Stream<Progress> crateApiConvertConvertImages({
    required String modelDir,
    required List<String> images,
    required String outDir,
    required String title,
    required OutFormat format,
    required int longEdge,
    required bool lowMemory,
  }) {
    final sink = RustStreamSink<Progress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(modelDir, serializer);
            sse_encode_list_String(images, serializer);
            sse_encode_String(outDir, serializer);
            sse_encode_String(title, serializer);
            sse_encode_out_format(format, serializer);
            sse_encode_u_32(longEdge, serializer);
            sse_encode_bool(lowMemory, serializer);
            sse_encode_StreamSink_progress_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 2,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiConvertConvertImagesConstMeta,
          argValues: [
            modelDir,
            images,
            outDir,
            title,
            format,
            longEdge,
            lowMemory,
            sink,
          ],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiConvertConvertImagesConstMeta =>
      const TaskConstMeta(
        debugName: "convert_images",
        argNames: [
          "modelDir",
          "images",
          "outDir",
          "title",
          "format",
          "longEdge",
          "lowMemory",
          "sink",
        ],
      );

  @override
  Stream<OcrProgress> crateApiTextlayerOcrImages({
    required String modelDir,
    required List<String> images,
    required int longEdge,
    required bool lowMemory,
  }) {
    final sink = RustStreamSink<OcrProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(modelDir, serializer);
            sse_encode_list_String(images, serializer);
            sse_encode_u_32(longEdge, serializer);
            sse_encode_bool(lowMemory, serializer);
            sse_encode_StreamSink_ocr_progress_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 3,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiTextlayerOcrImagesConstMeta,
          argValues: [modelDir, images, longEdge, lowMemory, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiTextlayerOcrImagesConstMeta => const TaskConstMeta(
    debugName: "ocr_images",
    argNames: ["modelDir", "images", "longEdge", "lowMemory", "sink"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<OcrProgress> dco_decode_StreamSink_ocr_progress_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<Progress> dco_decode_StreamSink_progress_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ConvertReport dco_decode_box_autoadd_convert_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_convert_report(raw);
  }

  @protected
  ConvertReport dco_decode_convert_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ConvertReport(
      docxPath: dco_decode_opt_String(arr[0]),
      xlsxPath: dco_decode_opt_String(arr[1]),
      pages: dco_decode_u_32(arr[2]),
      tables: dco_decode_u_32(arr[3]),
      failed: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<PageText> dco_decode_list_page_text(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_page_text).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TextBox> dco_decode_list_text_box(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_text_box).toList();
  }

  @protected
  OcrProgress dco_decode_ocr_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return OcrProgress_Loading();
      case 1:
        return OcrProgress_Page(
          index: dco_decode_u_32(raw[1]),
          total: dco_decode_u_32(raw[2]),
        );
      case 2:
        return OcrProgress_Done(pages: dco_decode_list_page_text(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  OutFormat dco_decode_out_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OutFormat.values[raw as int];
  }

  @protected
  PageText dco_decode_page_text(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PageText(
      boxes: dco_decode_list_text_box(arr[0]),
      error: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  Progress dco_decode_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return Progress_Loading();
      case 1:
        return Progress_Page(
          index: dco_decode_u_32(raw[1]),
          total: dco_decode_u_32(raw[2]),
        );
      case 2:
        return Progress_Writing();
      case 3:
        return Progress_Done(
          report: dco_decode_box_autoadd_convert_report(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  TextBox dco_decode_text_box(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TextBox(
      text: dco_decode_String(arr[0]),
      x0: dco_decode_f_32(arr[1]),
      y0: dco_decode_f_32(arr[2]),
      x1: dco_decode_f_32(arr[3]),
      y1: dco_decode_f_32(arr[4]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<OcrProgress> sse_decode_StreamSink_ocr_progress_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<Progress> sse_decode_StreamSink_progress_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ConvertReport sse_decode_box_autoadd_convert_report(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_convert_report(deserializer));
  }

  @protected
  ConvertReport sse_decode_convert_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_docxPath = sse_decode_opt_String(deserializer);
    var var_xlsxPath = sse_decode_opt_String(deserializer);
    var var_pages = sse_decode_u_32(deserializer);
    var var_tables = sse_decode_u_32(deserializer);
    var var_failed = sse_decode_list_String(deserializer);
    return ConvertReport(
      docxPath: var_docxPath,
      xlsxPath: var_xlsxPath,
      pages: var_pages,
      tables: var_tables,
      failed: var_failed,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<PageText> sse_decode_list_page_text(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PageText>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_page_text(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TextBox> sse_decode_list_text_box(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TextBox>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_text_box(deserializer));
    }
    return ans_;
  }

  @protected
  OcrProgress sse_decode_ocr_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return OcrProgress_Loading();
      case 1:
        var var_index = sse_decode_u_32(deserializer);
        var var_total = sse_decode_u_32(deserializer);
        return OcrProgress_Page(index: var_index, total: var_total);
      case 2:
        var var_pages = sse_decode_list_page_text(deserializer);
        return OcrProgress_Done(pages: var_pages);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  OutFormat sse_decode_out_format(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return OutFormat.values[inner];
  }

  @protected
  PageText sse_decode_page_text(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_boxes = sse_decode_list_text_box(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return PageText(boxes: var_boxes, error: var_error);
  }

  @protected
  Progress sse_decode_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return Progress_Loading();
      case 1:
        var var_index = sse_decode_u_32(deserializer);
        var var_total = sse_decode_u_32(deserializer);
        return Progress_Page(index: var_index, total: var_total);
      case 2:
        return Progress_Writing();
      case 3:
        var var_report = sse_decode_box_autoadd_convert_report(deserializer);
        return Progress_Done(report: var_report);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  TextBox sse_decode_text_box(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_x0 = sse_decode_f_32(deserializer);
    var var_y0 = sse_decode_f_32(deserializer);
    var var_x1 = sse_decode_f_32(deserializer);
    var var_y1 = sse_decode_f_32(deserializer);
    return TextBox(
      text: var_text,
      x0: var_x0,
      y0: var_y0,
      x1: var_x1,
      y1: var_y1,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_ocr_progress_Sse(
    RustStreamSink<OcrProgress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_ocr_progress,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_progress_Sse(
    RustStreamSink<Progress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_progress,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_convert_report(
    ConvertReport self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_convert_report(self, serializer);
  }

  @protected
  void sse_encode_convert_report(ConvertReport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.docxPath, serializer);
    sse_encode_opt_String(self.xlsxPath, serializer);
    sse_encode_u_32(self.pages, serializer);
    sse_encode_u_32(self.tables, serializer);
    sse_encode_list_String(self.failed, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_page_text(
    List<PageText> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_page_text(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_text_box(List<TextBox> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_text_box(item, serializer);
    }
  }

  @protected
  void sse_encode_ocr_progress(OcrProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case OcrProgress_Loading():
        sse_encode_i_32(0, serializer);
      case OcrProgress_Page(index: final index, total: final total):
        sse_encode_i_32(1, serializer);
        sse_encode_u_32(index, serializer);
        sse_encode_u_32(total, serializer);
      case OcrProgress_Done(pages: final pages):
        sse_encode_i_32(2, serializer);
        sse_encode_list_page_text(pages, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_out_format(OutFormat self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_page_text(PageText self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_text_box(self.boxes, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_progress(Progress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case Progress_Loading():
        sse_encode_i_32(0, serializer);
      case Progress_Page(index: final index, total: final total):
        sse_encode_i_32(1, serializer);
        sse_encode_u_32(index, serializer);
        sse_encode_u_32(total, serializer);
      case Progress_Writing():
        sse_encode_i_32(2, serializer);
      case Progress_Done(report: final report):
        sse_encode_i_32(3, serializer);
        sse_encode_box_autoadd_convert_report(report, serializer);
    }
  }

  @protected
  void sse_encode_text_box(TextBox self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_f_32(self.x0, serializer);
    sse_encode_f_32(self.y0, serializer);
    sse_encode_f_32(self.x1, serializer);
    sse_encode_f_32(self.y1, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
