// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'convert.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `convert_inner`, `load_gray`, `one_page`, `vacant`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

/// 把一组页图转成 docx / xlsx
///
/// - `model_dir` 放三个 .onnx 的目录; App 启动时从 bundle 里解出来
/// - `images` 按最终页序排好的图片路径, 顺序即页序
/// - `low_memory` 见 EngineOptions::low_memory(): 峰值省 ~130 MB, 几乎不费时间。
///   手机上没有理由关掉它
Stream<Progress> convertImages({
  required String modelDir,
  required List<String> images,
  required String outDir,
  required String title,
  required OutFormat format,
  required int longEdge,
  required bool lowMemory,
}) => RustLib.instance.api.crateApiConvertConvertImages(
  modelDir: modelDir,
  images: images,
  outDir: outDir,
  title: title,
  format: format,
  longEdge: longEdge,
  lowMemory: lowMemory,
);

/// 给 examples / 集成测试用的直通口子: 按手机上那套默认参数跑一遍, 出 docx
///
/// 单独开一个而不是把 convert_inner 设成 pub, 是因为 convert_inner 的八个
/// 参数里有一半在验证时永远是同一个值, 每次都抄一遍容易抄错。
Future<ConvertReport> convertForTest({
  required String modelDir,
  required List<String> images,
  required String outDir,
  required String title,
}) => RustLib.instance.api.crateApiConvertConvertForTest(
  modelDir: modelDir,
  images: images,
  outDir: outDir,
  title: title,
);

/// 一次转换的结果
class ConvertReport {
  final String? docxPath;
  final String? xlsxPath;

  /// 成功识别的页数
  final int pages;

  /// 识别到的表格张数(只在出 xlsx 时有意义)
  final int tables;

  /// 失败的页, 每条形如 "第 3 页: ..."。失败不中断, 其余页照出
  final List<String> failed;

  const ConvertReport({
    this.docxPath,
    this.xlsxPath,
    required this.pages,
    required this.tables,
    required this.failed,
  });

  @override
  int get hashCode =>
      docxPath.hashCode ^
      xlsxPath.hashCode ^
      pages.hashCode ^
      tables.hashCode ^
      failed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConvertReport &&
          runtimeType == other.runtimeType &&
          docxPath == other.docxPath &&
          xlsxPath == other.xlsxPath &&
          pages == other.pages &&
          tables == other.tables &&
          failed == other.failed;
}

/// 要出什么文件
enum OutFormat { docx, xlsx, both }

@freezed
sealed class Progress with _$Progress {
  const Progress._();

  /// 正在加载三个 ONNX 模型
  const factory Progress.loading() = Progress_Loading;

  /// 正在识别第 index 页(从 1 数), 共 total 页
  const factory Progress.page({required int index, required int total}) =
      Progress_Page;

  /// 正在写出文件
  const factory Progress.writing() = Progress_Writing;

  /// 全部做完, 带上结果。走流的最后一个事件, 不用函数返回值 ——
  /// flutter_rust_bridge 里带 StreamSink 的函数在 Dart 侧就是个 Stream,
  /// 返回值传不回去
  const factory Progress.done({required ConvertReport report}) = Progress_Done;
}
