// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'textlayer.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `ocr_inner`, `one_page`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// 逐页识别, 只出文字和坐标
Stream<OcrProgress> ocrImages({
  required String modelDir,
  required List<String> images,
  required int longEdge,
  required bool lowMemory,
}) => RustLib.instance.api.crateApiTextlayerOcrImages(
  modelDir: modelDir,
  images: images,
  longEdge: longEdge,
  lowMemory: lowMemory,
);

@freezed
sealed class OcrProgress with _$OcrProgress {
  const OcrProgress._();

  /// 正在加载三个 ONNX 模型
  const factory OcrProgress.loading() = OcrProgress_Loading;

  /// 正在识别第 index 页(从 1 数), 共 total 页
  const factory OcrProgress.page({required int index, required int total}) =
      OcrProgress_Page;

  /// 全部做完, 带上每页的文字框。页序跟传进来的 images 一致
  const factory OcrProgress.done({required List<PageText> pages}) =
      OcrProgress_Done;
}

/// 一页的识别结果
class PageText {
  final List<TextBox> boxes;

  /// 这一页为什么没认出来; 有值时 boxes 是空的
  ///
  /// 一页坏掉不该毁掉整批: 剩下的页照样有文字层, 这一页退化成纯图片
  final String? error;

  const PageText({required this.boxes, this.error});

  @override
  int get hashCode => boxes.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageText &&
          runtimeType == other.runtimeType &&
          boxes == other.boxes &&
          error == other.error;
}

/// 一行识别出来的字, 坐标归一化到 [0,1], 原点在页面左上角
///
/// 归一化而不是给像素: 识别是在缩到长边 2560 的灰度图上做的, 而 PDF 那边画的
/// 是原图, 两边尺寸对不上。归一化之后, 谁也不用知道对方缩放了多少。
class TextBox {
  final String text;
  final double x0;
  final double y0;
  final double x1;
  final double y1;

  const TextBox({
    required this.text,
    required this.x0,
    required this.y0,
    required this.x1,
    required this.y1,
  });

  @override
  int get hashCode =>
      text.hashCode ^ x0.hashCode ^ y0.hashCode ^ x1.hashCode ^ y1.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextBox &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          x0 == other.x0 &&
          y0 == other.y0 &&
          x1 == other.x1 &&
          y1 == other.y1;
}
